rasax:
    # initialUser is the user which is created upon the initial start of Rasa Enterprise
    initialUser:
        # username specifies a name of this user
        username: "admin"
        # password for the Rasa Enterprise user
        password: "rasa"
    # passwordSalt Rasa X uses to salt the user passwords
    passwordSalt: "asdfasd123123"
    # token Rasa X accepts as authentication token from other Rasa services
    token: "123123jkljdlfk123"
    # jwtSecret which is used to sign the jwtTokens of the users
    jwtSecret: "asdkfjlk123123"
    name: "rasa/rasa-x"
    tag: "0.39.3"
# rasa: Settings common for all Rasa containers
rasa:
    # token Rasa accepts as authentication token from other Rasa services
    token: "123mkmlsakdfjlkj"
    tag: "2.6.1-full"
    rabbitQueue: "rasa_production_events"
    additionalRabbitQueues:
    - "elk-log"
# RabbitMQ specific settings
rabbitmq:
    # rabbitmq settings of the subchart
    rabbitmq:
        # password which is used for the authentication
        password: "asdf123123joijasdf098"
# global settings of the used subcharts
global:
    # postgresql: global settings of the postgresql subchart
    postgresql:
        # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
        postgresqlPassword: "asdfkjasldkj123123"
    # redis: global settings of the redis subchart
    redis:
        # password to use in case there no external secret was provided
        password: "asdkfjalsk123123"
debugMode: true
images:
    imagePullSecrets:
    - name: "gcr-pull-secret"
nginx:
    enabled: false
ingress:
    enabled: true